twitter_query: "#indihome OR #telkomIndonesia OR #telkom OR #gangguanTelkom lang:id"
max_tweets: 10
embedding_model: "all-MiniLM-L6-v2"
qdrant_collection: "multi_source"
chunk_size: 256
chunk_overlap: 32
top_k: 5
pdf_path: "tiket_penanganan.pdf"
twitter_bearer_token: ""
harvest_output: "tweets_harvest.csv"
score_ratio: 0.8      # 0.7-0.9 umum
min_score: 0.2        # 0.0-0.3, naikkan jika ingin lebih ketat
openai_temperature: 0.5