twitter_query: "#indihome OR #telkomIndonesia OR #telkom OR #gangguanTelkom lang:id"
max_tweets: 10
embedding_model: "all-MiniLM-L6-v2"
qdrant_collection: "multi_source"
openai_api_key: "YOUR_OPENAI_KEY"
chunk_size: 256
chunk_overlap: 32
top_k: 5
pdf_path: "tiket_penanganan.pdf"
twitter_bearer_token: "4dbb9dbd4d1c84d86c8815b0c93d6c0acad24f32"
harvest_output: "tweets_harvest.csv"
