version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  pipeline:
    build: .
    depends_on:
      - qdrant
    volumes:
      - .:/app
    working_dir: /app
    command: python nyobain/integrated_twitter_pipeline.py

volumes:
  qdrant_data:
